# Travis CI configuration file for WordPoints.

language: php

php:
    - 7.0

env:
    - TRAVISCI_RUN=phpunit WP_VERSION=develop

dist: trusty

sudo: false

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

before_script:
    - export WORDPOINTS_PROJECT_TYPE=wordpoints
    - export DEV_LIB_DEBUG=1
    - export DEV_LIB_PATH=dev-lib
    - if [ -e .wordpoints-dev-lib-config.sh ]; then source .wordpoints-dev-lib-config.sh; fi
    - source $DEV_LIB_PATH/travis/before_script.sh

script:
    - wpcept-run

after_script:
    - source $DEV_LIB_PATH/travis/after_script.sh
